### ISSUE TITLE
Build Errors in Xcode

### ISSUE THREAD

**Issue by wilu222** [IGRSoft/KisMac2#106]
OSX 10.12

Several errors popped up telling me to validate project settings for BiGeneric project, KiSmac2 project, and BIGL project. As well as this:

KisMac2
Code Signing Error: No account for team "DMP42GVPJ3". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.
Code Signing Error: No signing certificate "Mac Development" found:  No "Mac Development" signing certificate matching team ID "DMP42GVPJ3" with a private key was found.

I don't have a developer account - I added my personal account to the accounts menu and played around with the code signing settings (current on Don't Sign) but it still doesn't work.

**Comment by rmnoff** [comment]
I have the same issue.

**Comment by wilu222** [comment]
I decided to just install Kali Linux on a USB and use aircrack instead. Oh well

**Comment by Beyarz** [comment]
@bgillys picture solved the issue.
