### ISSUE TITLE
Many different BSSIDs reported for same SSID

### ISSUE THREAD

**Issue by alimony** [IGRSoft/KisMac2#29]
When scanning, I get many different BSSID values for the same SSID, also resulting in a lot of duplicate SSIDs in the table of networks. See attached screenshot (first part of SSID redacted, but they are all identical):

![duplicate_ssids](https://cloud.githubusercontent.com/assets/331091/5328804/d15a00b8-7d8f-11e4-9160-d80f1050e331.png)

**Comment by zachberger** [comment]
If this is an enterprise network that is not unexpected behavior. Each base station has its own BSSID.

**Comment by orinem** [comment]
See also issue #45.

I had many BSSIDs differing only in the last byte displayed - which lead to the discovery that 7 bytes are displayed when there should only be six, as can be seen in alimony's screenshot.

**Comment by iKorich** [comment]
Done
