### ISSUE TITLE
Frequent Crashes - Exception Type:  EXC_BAD_ACCESS (SIGSEGV) - Exception Codes: EXC_I386_GPFLT

### ISSUE THREAD

**Issue by CosmicVoyager** [IGRSoft/KisMac2#40]
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: EXC_I386_GPFLT

Crash report
http://pastebin.com/ABqWQUf3

**Comment by iKorich** [comment]
cache has been fixed
