### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by tkoyn** [IGRSoft/KisMac2#42]
I downloaded source with a clone and found that to compile there was a missing resource in the materials checked into GIT, vendor.db. Once I found this file inside one of your builds and put it in my source tree, I was able to build.

Also the zip download version of the source did not include some of the Subprojects files I received in the  git clone.

**Comment by iKorich** [comment]
that file generating with "Update vendors.db" script in xcode build phases
It takes a while

**Comment by tkoyn** [comment]
I had a build error when I first tried to build. Then it went away when I added the file manually in my source materials. I didn't see how it was being generated.
