### ISSUE TITLE
On many starts of the app, five buttons dead

### ISSUE THREAD

**Issue by tkoyn** [IGRSoft/KisMac2#44]
Often and intermittently, while running in Yosemite, the app starts with the following buttons dead and unresponsive: Show Networks, Show Traffic, Show Map, Show Details, Toggle Scan.

Tracing with debugger, I find execution gets into selfSendEvent in ScriptingEngine.m, where the program is sending itself an AppleEvent with AESend. Then on a working run, it goes through two levels of assembly language to reach the performance of the command in ScriptAdditions.m in methods such as toggleScan.

On other executions of the app when its not working, we get to the AESend call and into one assembly language level, then we never reach ScriptAdditions and the five buttons each appear to the user to do nothing.

**Comment by iKorich** [comment]
AESend can't connect AppleEvent with toggleScan func
App didn't read kismac.scriptSuite

**Comment by tkoyn** [comment]
How should this be fixed? I wouldn't mind if the app lost AppleScript support.

**Comment by iKorich** [comment]
I do not have a time to find way to fix it((

**Comment by iKorich** [comment]
duplicate Issue #21

**Comment by tkoyn** [comment]
No I don't think this issue is the same as 21.

**Comment by tkoyn** [comment]
Can you make the program invoke the functions more directly, instead of the application sending itself Apple Events, when any of the five buttons I reference are clicked?

Do you have any idea why the program intermittently can't send itself Apple Events?

**Comment by tkoyn** [comment]
Just saw your commit for this issue. To what extent does this help the issue?

https://github.com/IGRSoft/KisMac2/commit/17e827d5c73843d8bc7a109e0740292816d4edc8

I will get the new code and try it out when I get a chance.

Thanks for looking at this.

**Comment by iKorich** [comment]
I want remove that Apple Events, but time, time and time...
You can make a fork, rewrite it and make pull request

**Comment by tkoyn** [comment]
Just curious, what did your commit marked code review accomplish? To what extent does it help the buttons work?
