### ISSUE TITLE
Issue 48 was closed too soon

### ISSUE THREAD

**Issue by tkoyn** [IGRSoft/KisMac2#52]
I am continuing to have issues with the build finding the header files in BIGeneric and BIGL even after I checkout the submodules as you describe on the how to build information. I have the header files involved, but Xcode is not finding them in the expected locations.

**Comment by tkoyn** [comment]
Please test this issue by checking out KisMac from GIT into a new black folder and following your build instructions exactly on the new copy. You will find issue 42 with the missing resource and issue 48 should not have been closed, as they are still issues.

**Comment by iKorich** [comment]
are you work with KisMac2.xcworkspace?

**Comment by tkoyn** [comment]
Oops, sorry grabbed the wrong file, but still issue 42 exists, as I still had to manually put in the vendor.db file to complete the build.

**Comment by iKorich** [comment]
https://www.youtube.com/watch?v=LdLpvB-UVAQ&ab_channel=VitaliiParovishnyk
everything works without problems

**Comment by orinem** [comment]
It builds for me without problems if I follow the instructions in the readme - Xcode 6.4 on Yosemite.

**Comment by tkoyn** [comment]
OK, I see. I had an issue with a local firewall that erroneously blocked the download from OUI. You may close this.

**Comment by iKorich** [comment]
17ee0fd5b9526da16005e62304b300c1f9670796
