### ISSUE TITLE
Is KisMac2 supported in Yosemite?(10.10.4)

### ISSUE THREAD

**Issue by LemonShake** [IGRSoft/KisMac2#59]

**Comment by orinem** [comment]
The latest works for me using the builtin adapter on my Mac Mini.

Please raise an issue if something specific doesn't work.

**Comment by orinem** [comment]
I do all my testing with Yosemite and the Airport Extreme and RTL8187 drivers work for me.

I don't know of any Yosemite specific problems, so I'm closing this issue.

If something specific isn't working (Yosemite or not), please raise a separate issue.
