### ISSUE TITLE
RTL8187 random behavior

### ISSUE THREAD

**Issue by orinem** [IGRSoft/KisMac2#60]
It goes something like this (OS X Yosemite, late 2012 Mac Mini):

Select USB RTL8187 as the only capture device
Start scan
No packets are captured, no networks are displayed

Restart KisMac2
Start scan
Only small packets are captured (you need to set a breakpoint in _interruptReceived to look at the length), no networks displayed

Unplug adapter & plug back in.
Restart KisMac2
Start scan
Seems to be working, packets captured and networks displayed

I'm looking into it.

**Comment by tkoyn** [comment]
Thank you orinem for working on Kismac and this issue. Would you have any comments on #57 of #58 that I had posted?

https://github.com/IGRSoft/KisMac2/issues/57
https://github.com/IGRSoft/KisMac2/issues/58

**Comment by orinem** [comment]
Sorry, not at the moment.  Perhaps in the next week or so.

**Comment by orinem** [comment]
Closing this issue.  I've not seen any strange behavior with the fix.
