### ISSUE TITLE
PrefsDriver.xib crashes XCode 5.1.1

### ISSUE THREAD

**Issue by tmcsys** [IGRSoft/KisMac2#77]
Could someone please take a look at that xib in an older version of Xcode?
Some of us just aren't up to keeping with Apple's relentless upgrades.  I'm on 10.8.5 (and still wondering if it's really better than Snow Leopard).
It's hard to believe an xml file can crash a development system.  That's right, crash.  No error, no warning, XCode just goes away.
Say what you like about Microsoft, but they pay attention to backwards compatibility.

Thanks.

From the crash log:

Application Specific Information:
ProductBuildVersion: 5B1008
ASSERTION FAILURE in /SourceCache/IDEInterfaceBuilder/IDEInterfaceBuilder-5056/InterfaceBuilderKit/Document/Archiving/IBDocumentUnarchiver.m:224
Details:  Failed to unarchive an instance of NSColor
Object:   <IBDocumentUnarchiver: 0x7fd9860a00b0>
Method:   -unarchiveObjectFromElement:
Thread:   <NSThread: 0x7fd97ac14ec0>{name = (null), num = 1}
Hints:   None

**Comment by iKorich** [comment]
project for Xcode 7+ only
