### ISSUE TITLE
igrsoft.com/en contains harmful programs?

### ISSUE THREAD

**Issue by felixfischer** [IGRSoft/KisMac2#79]
Google Chrome is currently blocking access to the [KisMac2 download page](http://www.igrsoft.com/en/).
I am being warned that "igrsoft.com/en contains harmful programs."

See Google's [Safe Browsing Report for igrsoft.com/en](https://www.google.com/transparencyreport/safebrowsing/diagnostic/index.html#url=http://www.igrsoft.com/en/) for further information.

What is happening there?

**Comment by iKorich** [comment]
Hm...

My site doesn't contain malware apps.
I'll try remove that warning.

Thank you!

**Comment by kubark42** [comment]
Yup, definitely getting this warning as well. Using Firefox on OSX10.10.5.

**Comment by iKorich** [comment]
Warning has been removed
