### ISSUE TITLE
Xcode can't build.

### ISSUE THREAD

**Issue by daddadhad** [IGRSoft/KisMac2#80]
I am on OSX 10.7.5 (yes 64-bit) and I ran the installation but when I went to build kismac in Xcode I got an error under BIGeneric and it says: 
Workspace Integrity
Couldn't load project

When I click to get to the error it says that the file couldn't be opened. No matter what I do this always happens. Reinstalled 3 times; same thing,

**Comment by iKorich** [comment]
min macos 10.9

**Comment by BSVogler** [comment]
@iKorich readme says 10.7 so readme should then be updated

**Comment by iKorich** [comment]
done
