### ISSUE TITLE
Cannot download - 404 Error

### ISSUE THREAD

**Issue by ecnepsnai** [IGRSoft/KisMac2#83]
The download link on your site does not work - 404 not found: https://downloads.igrsoft.com/beta/KisMac2.zip

Perhaps you should upload binaries to Github instead as it's far more reliable.

**Comment by sscotth** [comment]
The download link in the README is http://downloads.igrsoft.com/beta/KisMac2.zip which works

**Comment by ecnepsnai** [comment]
Appears to work now.
