### ISSUE TITLE
How do you build ?

### ISSUE THREAD

**Issue by geostant** [IGRSoft/KisMac2#85]
There is no build folder or file...

**Comment by TheWilyRacoon** [comment]
You have to use XCode to build

**Comment by TobiAkatsuki** [comment]
Keep getting errors on xcode, can you tell me how to build this with xcode?

**Comment by geostant** [comment]
Installed xCode but couldn't build,
after a while it failed.

**Comment by felangga** [comment]
Is there any compiled kismac ?

**Comment by iKorich** [comment]
fixed
