### ISSUE TITLE
Building from Xcode 8.0 Error

### ISSUE THREAD

**Issue by buglinjo** [IGRSoft/KisMac2#88]
When I start building it says "linker command failed with exit code 1 (use -v to see invocation)"
<img width="1280" alt="screen shot 2016-09-30 at 16 16 55" src="https://cloud.githubusercontent.com/assets/1254208/19005621/8dde64a0-8729-11e6-9bcf-3103a38a3c87.png">

**Comment by stefan0p** [comment]
I have the same issue, osx 10.12.1

**Comment by yves-vogl** [comment]
Any solution yet?

**Comment by denisafanasev** [comment]
I've got the same with osx 10.12.3

Could somebody share a solution?

**Comment by orinem** [comment]
Try adding /usr/local/opt/openssl/lib to "Library Search Paths" in the KisMac2 target.

**Comment by denisafanasev** [comment]
Thank you very much! It helped!

**Comment by denisafanasev** [comment]
Why not to include it into default project setting? I mean out to master branch.

**Comment by gallairea** [comment]
Please could you give some details about this add? I have the same error but I don't find the folders usr/local/opt/openssl/lib ...
Thanks !

**Comment by swosko** [comment]
That worked for me (just adding /usr/local/opt/openssl/lib to the search paths). I never would have found it.

**Comment by iKorich** [comment]
fixed
