### ISSUE TITLE
Cannot build: the clone of BIGeneric/Submodules/BIGL fails with 404 

### ISSUE THREAD

**Issue by jhelm** [IGRSoft/KisMac2#97]
Hello,

The link "https://github.com/IGRSoft/BIGeneric/tree/master/Submodules/BIGL @ 7c772" (https://github.com/IGRSoft/BIGL/tree/7c77e2e5bb9071a376ea9a17ef3602acbfdc7062) returns a 404, so the git submodule update fails and the source tree is incomplete. Thus the build fails when it can't find 'BIGL/BIGL.h'.

Just FYI and thanks for preserving KisMac!

/John

**Comment by iKorich** [comment]
Fixed

**Comment by BSVogler** [comment]
@iKorich I just downloaded the latest version and I get the same error

**Comment by jhelm** [comment]
Same happened to me. It worked when I removed the entire subtree and re-cloned from the  beginning.

**Comment by iKorich** [comment]
Was problem with tree((
need clone again
